import { MarketplaceData } from "./types";

export const demoData: MarketplaceData = {
  users: [
    { id: "u-buyer-1", name: "杭州北辰智能科技", email: "mira@northstar.ai", role: "buyer", createdAt: "2026-04-20" },
    { id: "u-buyer-2", name: "城野生活电商", email: "leo@urbanline.co", role: "buyer", createdAt: "2026-04-24" },
    { id: "u-buyer-3", name: "云上课程工作室", email: "course@cloudclass.cn", role: "buyer", createdAt: "2026-05-02" },
    { id: "u-admin-1", name: "平台运营管理员", email: "admin@marketplace.dev", role: "admin", createdAt: "2026-04-01" },
    { id: "u-creator-1", name: "阿鹿影像工坊", email: "ava@studio.ai", role: "creator", createdAt: "2026-04-10" },
    { id: "u-creator-2", name: "开物短视频", email: "kai@motion.ai", role: "creator", createdAt: "2026-04-12" },
    { id: "u-creator-3", name: "露娜视觉", email: "luna@visuals.ai", role: "creator", createdAt: "2026-04-13" },
    { id: "u-creator-4", name: "诺亚数字人实验室", email: "noah@avatar.ai", role: "creator", createdAt: "2026-04-14" },
    { id: "u-creator-5", name: "艾瑞电商内容", email: "iris@commerce.ai", role: "creator", createdAt: "2026-04-15" },
    { id: "u-creator-6", name: "回声广告组", email: "echo@ads.ai", role: "creator", createdAt: "2026-04-17" },
    { id: "u-creator-7", name: "薇拉品牌AI", email: "vera@brand.ai", role: "creator", createdAt: "2026-04-19" },
    { id: "u-creator-8", name: "像素港产品图", email: "pixel@harbor.ai", role: "creator", createdAt: "2026-04-21" },
    { id: "u-creator-9", name: "合成空间", email: "synth@crew.ai", role: "creator", createdAt: "2026-04-22" },
    { id: "u-creator-10", name: "青苔内容包", email: "moss@content.ai", role: "creator", createdAt: "2026-04-23" }
  ],
  buyerProfiles: [
    {
      id: "bp-1",
      userId: "u-buyer-1",
      companyName: "杭州北辰智能科技",
      displayName: "北辰智能内容需求中心",
      avatarUrl: "北",
      profileSlogan: "长期寻找懂智能硬件和B端软件的AIGC内容伙伴",
      industry: "智能硬件 / SaaS",
      location: "杭州",
      companyIntro: "专注智能办公硬件和企业效率工具，常年需要产品短视频、SaaS说明视频和电商内容素材。",
      verificationType: "enterprise",
      contactEmail: "mira@northstar.ai",
      contactPhone: "0571-8800-1024",
      websiteUrl: "https://northstar.example.com",
      socialUrl: "https://www.xiaohongshu.com/user/profile/northstar",
      serviceArea: "全国远程协作，杭州可线下面谈",
      businessLicenseFile: "杭州北辰智能科技营业执照.pdf",
      qualificationFiles: ["品牌授权书.pdf", "智能台灯产品检测说明.pdf"],
      verified: true,
      cover: "linear-gradient(135deg, #153f31, #2457c5)"
    },
    {
      id: "bp-2",
      userId: "u-buyer-2",
      companyName: "城野生活电商",
      displayName: "城野生活内容组",
      avatarUrl: "城",
      profileSlogan: "家居日用商家，持续招募商品图和短视频创作者",
      industry: "家居日用 / 电商",
      location: "上海",
      companyIntro: "经营家居收纳、清洁用品和生活方式小商品，主要在淘宝、小红书和抖音渠道做内容测试。",
      verificationType: "individual_business",
      contactEmail: "leo@urbanline.co",
      contactPhone: "021-6800-2210",
      websiteUrl: "https://urbanline.example.com",
      socialUrl: "https://www.douyin.com/user/urbanline",
      serviceArea: "全国远程协作",
      businessLicenseFile: "城野生活电商营业执照.pdf",
      qualificationFiles: ["商标使用证明.pdf"],
      verified: true,
      cover: "linear-gradient(135deg, #16724f, #a86612)"
    },
    {
      id: "bp-3",
      userId: "u-buyer-3",
      companyName: "云上课程工作室",
      displayName: "云上课程内容需求",
      avatarUrl: "云",
      profileSlogan: "在线课程团队，重点寻找数字人和课程短视频伙伴",
      industry: "在线教育 / 知识服务",
      location: "成都",
      companyIntro: "面向职场人提供线上课程和训练营，需要数字人口播、课程预告和社群转化内容。",
      verificationType: "school",
      contactEmail: "course@cloudclass.cn",
      contactPhone: "028-6100-8899",
      websiteUrl: "https://cloudclass.example.com",
      socialUrl: "https://www.bilibili.com/cloudclass",
      serviceArea: "全国远程协作",
      businessLicenseFile: "云上课程工作室主体资质.pdf",
      qualificationFiles: ["课程版权说明.pdf"],
      verified: false,
      cover: "linear-gradient(135deg, #2457c5, #1d8a99)"
    }
  ],
  creators: [
    {
      id: "c-1",
      userId: "u-creator-1",
      name: "阿鹿影像工坊",
      title: "AI商品短视频工作室",
      location: "杭州",
      bio: "把商品卖点整理成脚本、分镜、AI素材和成片，适合新品首发和电商投放。",
      resume: "服务过美妆、智能硬件和众筹产品团队，擅长从产品卖点提炼到短视频脚本、分镜和成片包装。",
      skills: ["Runway", "剪映", "分镜脚本", "电商"],
      categories: ["AI Short Video"],
      portfolio: ["美妆新品短片", "天猫15秒广告", "众筹产品预热视频"],
      portfolioItems: [
        {
          id: "pf-c1-1",
          title: "智能硬件新品15秒短视频",
          category: "AI Short Video",
          description: "为智能台灯整理3版开头钩子、产品特写和中文字幕包装，用于小红书和抖音投放测试。",
          url: "https://example.com/ava-lamp",
          public: true
        },
        {
          id: "pf-c1-2",
          title: "美妆新品首发短片",
          category: "AI Short Video",
          description: "完成脚本、分镜、AI素材和竖屏成片，突出质地、使用场景和新品利益点。",
          url: "https://example.com/ava-beauty",
          public: true
        }
      ],
      servicePackages: [
        {
          id: "sp-c1-1",
          name: "15秒短视频基础包",
          price: 1200,
          deliveryDays: 5,
          revisions: 1,
          deliverables: ["脚本", "15秒竖屏成片", "中文字幕"],
          description: "适合单品测试、轻量种草和新品预热。"
        },
        {
          id: "sp-c1-2",
          name: "投放素材标准包",
          price: 3200,
          deliveryDays: 7,
          revisions: 2,
          deliverables: ["3版开头钩子", "分镜", "竖屏成片", "封面图"],
          description: "适合信息流素材A/B测试，交付后可继续追加变体。"
        }
      ],
      priceMin: 880,
      priceMax: 4500,
      completedProjects: 38,
      rating: 4.9,
      responseTime: "2小时",
      verified: true,
      identityType: "enterprise",
      verificationType: "enterprise",
      credentialFile: "阿鹿影像工坊营业执照.pdf",
      qualificationFiles: ["作品授权展示说明.pdf"],
      avatarUrl: "鹿",
      displayName: "阿鹿影像工坊",
      profileSlogan: "AI商品短视频工作室",
      websiteUrl: "https://ava-studio.example.com",
      socialUrl: "https://www.xiaohongshu.com/user/profile/ava-studio",
      serviceArea: "全国远程协作，杭州可线下面谈",
      contactEmail: "ava@studio.ai",
      contactPhone: "0571-8800-2001",
      cover: "linear-gradient(135deg, #16724f, #1d8a99)"
    },
    {
      id: "c-2",
      userId: "u-creator-2",
      name: "开物短视频",
      title: "效果广告短视频创作者",
      location: "上海",
      bio: "制作UGC风格AI广告、前三秒钩子、多版本脚本和竖屏投放素材。",
      resume: "长期服务效果广告和App拉新团队，熟悉多钩子脚本、投放素材变体和快速复盘迭代。",
      skills: ["AI广告", "钩子脚本", "剪辑", "短视频投放"],
      categories: ["AI Short Video", "Digital Human"],
      portfolio: ["SaaS解释视频", "健身产品广告包", "App拉新素材"],
      portfolioItems: [
        {
          id: "pf-c2-1",
          title: "SaaS解释视频",
          category: "AI Short Video",
          description: "将复杂B端功能拆成问题、场景、收益三段式脚本，交付30秒竖屏解释视频。",
          url: "https://example.com/kai-saas",
          public: true
        },
        {
          id: "pf-c2-2",
          title: "App拉新素材包",
          category: "AI Short Video",
          description: "围绕不同人群痛点制作多钩子短视频素材，便于投放团队快速复盘。",
          url: "https://example.com/kai-app",
          public: true
        }
      ],
      servicePackages: [
        {
          id: "sp-c2-1",
          name: "广告钩子测试包",
          price: 2600,
          deliveryDays: 4,
          revisions: 1,
          deliverables: ["5条钩子脚本", "2条竖屏成片", "字幕文件"],
          description: "适合拉新、表单线索和轻量投放验证。"
        },
        {
          id: "sp-c2-2",
          name: "信息流素材冲刺包",
          price: 5800,
          deliveryDays: 8,
          revisions: 2,
          deliverables: ["10条脚本", "4条成片", "封面", "复盘建议"],
          description: "适合需要快速起量的广告账户和新品活动。"
        }
      ],
      priceMin: 1200,
      priceMax: 6200,
      completedProjects: 56,
      rating: 4.8,
      responseTime: "1小时",
      verified: true,
      identityType: "enterprise",
      verificationType: "enterprise",
      credentialFile: "开物短视频营业执照.pdf",
      qualificationFiles: ["广告素材案例授权.pdf"],
      avatarUrl: "开",
      displayName: "开物短视频",
      profileSlogan: "效果广告短视频创作者",
      websiteUrl: "https://kai-motion.example.com",
      socialUrl: "https://www.douyin.com/user/kai-motion",
      serviceArea: "全国远程协作",
      contactEmail: "kai@motion.ai",
      contactPhone: "021-6800-1122",
      cover: "linear-gradient(135deg, #2457c5, #16a085)"
    },
    {
      id: "c-3",
      userId: "u-creator-3",
      name: "露娜视觉",
      title: "AI商品图与海报设计师",
      location: "广州",
      bio: "为电商、品牌活动和小红书内容生成主图、场景图、海报套图和视觉规范。",
      resume: "专注AI商品图、海报和品牌视觉，参与过护肤品、厨房用品和生活方式素材库项目。",
      skills: ["Midjourney", "PS精修", "商品图", "品牌视觉"],
      categories: ["Image Design"],
      portfolio: ["护肤品场景图", "厨房用品详情图", "生活方式素材库"],
      portfolioItems: [
        {
          id: "pf-c3-1",
          title: "护肤品场景图",
          category: "Image Design",
          description: "为护肤套装生成浴室、旅行和礼盒场景图，统一光线、材质和品牌色。",
          url: "https://example.com/luna-skincare",
          public: true
        },
        {
          id: "pf-c3-2",
          title: "厨房用品详情图",
          category: "Image Design",
          description: "围绕收纳、防水和容量卖点完成电商详情页素材，兼顾主图点击和详情阅读。",
          url: "https://example.com/luna-kitchen",
          public: true
        }
      ],
      servicePackages: [
        {
          id: "sp-c3-1",
          name: "商品主图精修包",
          price: 699,
          deliveryDays: 3,
          revisions: 1,
          deliverables: ["主图1张", "场景图2张", "基础精修"],
          description: "适合已有产品照片、需要快速上架的商品。"
        },
        {
          id: "sp-c3-2",
          name: "电商视觉套图包",
          price: 2200,
          deliveryDays: 6,
          revisions: 2,
          deliverables: ["主图", "详情页图", "活动横幅", "可编辑源文件"],
          description: "适合新品上架、活动页和社媒同步投放。"
        }
      ],
      priceMin: 399,
      priceMax: 2800,
      completedProjects: 71,
      rating: 4.95,
      responseTime: "3小时",
      verified: true,
      identityType: "individual",
      verificationType: "individual",
      credentialFile: "露娜视觉个人实名核验记录",
      qualificationFiles: ["平台作品展示授权.pdf"],
      avatarUrl: "露",
      displayName: "露娜视觉",
      profileSlogan: "AI商品图与海报设计师",
      websiteUrl: "https://luna-visual.example.com",
      socialUrl: "https://www.behance.net/luna-visual",
      serviceArea: "全国远程协作",
      contactEmail: "luna@visuals.ai",
      contactPhone: "020-8100-3344",
      cover: "linear-gradient(135deg, #166b8f, #c06f24)"
    },
    {
      id: "c-4",
      userId: "u-creator-4",
      name: "诺亚数字人实验室",
      title: "数字人口播交付团队",
      location: "北京",
      bio: "提供数字人出镜、脚本润色、配音口型、字幕和品牌模板，适合课程、SaaS和招商说明。",
      resume: "数字人口播交付团队，覆盖课程介绍、直播预热、B端产品演示和招商说明类内容。",
      skills: ["数字人", "脚本", "配音", "字幕"],
      categories: ["Digital Human", "AIGC Training"],
      portfolio: ["课程介绍口播", "直播预热视频", "B端产品演示"],
      trainingProfile: {
        topics: ["数字人实战", "AI课程内容", "AI营销视频"],
        formats: ["online", "workshop", "offline"],
        audience: ["市场团队", "课程团队", "企业培训负责人"],
        cities: ["全国线上", "北京", "天津"],
        caseStudies: ["为在线教育团队完成数字人口播工作坊，25人，1天实操", "为SaaS客户成功团队设计AI讲解视频内训"],
        materials: ["课件", "练习素材", "工具清单", "课后答疑"],
        pricingNote: "支持半日工作坊、1天内训和按项目陪跑报价。",
        customizable: true
      },
      priceMin: 1500,
      priceMax: 8800,
      completedProjects: 29,
      rating: 4.7,
      responseTime: "4小时",
      verified: true,
      cover: "linear-gradient(135deg, #33423b, #2457c5)"
    },
    {
      id: "c-5",
      userId: "u-creator-5",
      name: "艾瑞电商内容",
      title: "AIGC电商内容服务商",
      location: "深圳",
      bio: "组合交付商品图、短视频、详情文案和平台上架素材，适合中小商家快速测款。",
      resume: "面向中小商家提供电商内容包，熟悉淘宝、京东、亚马逊等渠道的图片和短视频素材。",
      skills: ["详情图", "短视频", "卖点文案", "淘宝京东"],
      categories: ["AI Short Video", "Image Design"],
      portfolio: ["亚马逊图片包", "宠物用品短片", "节日营销视觉"],
      priceMin: 680,
      priceMax: 5200,
      completedProjects: 44,
      rating: 4.85,
      responseTime: "2小时",
      verified: true,
      cover: "linear-gradient(135deg, #0d563a, #a86612)"
    },
    {
      id: "c-6",
      userId: "u-creator-6",
      name: "回声广告组",
      title: "AI广告批量测试团队",
      location: "成都",
      bio: "按投放角度批量生成广告素材，支持多版本脚本、画面、字幕和快速复盘迭代。",
      resume: "擅长广告素材批量测试，为DTC、游戏、教育线索广告提供多版本创意和字幕包装。",
      skills: ["广告变体", "信息流", "Runway", "迭代"],
      categories: ["AI Short Video"],
      portfolio: ["DTC广告冲刺", "游戏上线素材", "教育线索广告"],
      priceMin: 1000,
      priceMax: 5800,
      completedProjects: 33,
      rating: 4.65,
      responseTime: "1天",
      verified: false,
      cover: "linear-gradient(135deg, #2457c5, #a86612)"
    },
    {
      id: "c-7",
      userId: "u-creator-7",
      name: "薇拉品牌AI",
      title: "AI品牌视觉主理人",
      location: "杭州",
      bio: "为新消费、教育和本地品牌搭建统一的AI视觉方向、提示词体系和内容模板。",
      resume: "品牌AI视觉主理人，参与过创始人形象、咖啡店视觉包和课程宣传海报项目。",
      skills: ["视觉指导", "品牌套件", "提示词系统", "设计"],
      categories: ["Image Design"],
      portfolio: ["创始人形象系统", "咖啡店视觉包", "课程宣传海报"],
      priceMin: 1500,
      priceMax: 9800,
      completedProjects: 22,
      rating: 4.9,
      responseTime: "5小时",
      verified: true,
      cover: "linear-gradient(135deg, #16724f, #c45d4c)"
    },
    {
      id: "c-8",
      userId: "u-creator-8",
      name: "像素港产品图",
      title: "AI商品场景图生成师",
      location: "宁波",
      bio: "擅长商品白底图优化、使用场景扩展、详情页素材和目录图更新。",
      resume: "专注商品场景图和目录图更新，服务过家具、户外装备和小家电产品素材项目。",
      skills: ["商品渲染", "精修", "目录图", "Midjourney"],
      categories: ["Image Design"],
      portfolio: ["家具目录图", "户外装备场景", "小家电渲染套图"],
      priceMin: 300,
      priceMax: 2200,
      completedProjects: 61,
      rating: 4.75,
      responseTime: "2小时",
      verified: true,
      cover: "linear-gradient(135deg, #1d8a99, #33423b)"
    },
    {
      id: "c-9",
      userId: "u-creator-9",
      name: "合成空间",
      title: "数字人与声音流程团队",
      location: "武汉",
      bio: "交付产品讲解、培训课程和多语言说明类数字人视频，支持声音、字幕和模板化更新。",
      resume: "数字人与声音流程团队，覆盖保险产品讲解、HR培训和零售培训类数字人视频。",
      skills: ["数字人", "声音克隆", "字幕", "培训视频"],
      categories: ["Digital Human", "AI Short Video", "AIGC Training"],
      portfolio: ["保险产品讲解", "HR入职培训", "零售培训短片"],
      trainingProfile: {
        topics: ["AI办公提效", "HR培训视频", "零售门店培训", "数字人课件"],
        formats: ["online", "offline", "coaching"],
        audience: ["HR团队", "零售培训团队", "运营团队"],
        cities: ["全国线上", "武汉", "长沙", "杭州"],
        caseStudies: ["为HR团队制作入职培训数字人流程并辅导内部更新", "为零售团队完成门店培训短片和课后资料包"],
        materials: ["课件", "录播", "练习任务", "字幕模板"],
        pricingNote: "支持按场、按天或长期内容更新陪跑。",
        customizable: true
      },
      priceMin: 1800,
      priceMax: 10800,
      completedProjects: 18,
      rating: 4.6,
      responseTime: "6小时",
      verified: true,
      cover: "linear-gradient(135deg, #0d563a, #2457c5)"
    },
    {
      id: "c-10",
      userId: "u-creator-10",
      name: "青苔内容包",
      title: "AI内容包运营者",
      location: "苏州",
      bio: "为轻量团队打包交付图片、短视频、字幕文案和修改轮次，适合持续内容更新。",
      resume: "AI内容包运营者，适合餐饮开业、教育内容套件和B端周更内容的长期协作。",
      skills: ["内容包", "字幕文案", "图片", "修改"],
      categories: ["AI Short Video", "Image Design", "Digital Human"],
      portfolio: ["餐饮开业内容包", "教育内容套件", "B端周更内容"],
      priceMin: 500,
      priceMax: 4800,
      completedProjects: 47,
      rating: 4.82,
      responseTime: "3小时",
      verified: true,
      cover: "linear-gradient(135deg, #16724f, #2457c5)"
    }
  ],
  projects: [
    {
      id: "p-1",
      buyerId: "u-buyer-1",
      title: "智能台灯新品15秒AI短视频",
      description: "需要三个开头钩子、产品特写、中文字幕和竖屏成片，用于抖音和小红书投放。",
      category: "AI Short Video",
      budget: 3600,
      deadline: "2026-06-02",
      status: "matching",
      referenceFile: "台灯需求说明.pdf",
      agentBrief: {
        objective: "为智能台灯制作小红书和抖音投放内容，突出护眼、氛围灯和桌面美学。",
        audience: "25-35岁城市白领、学生和桌搭爱好者",
        style: "高级、干净、有科技感，适合种草转化",
        deliverables: ["15-30秒竖屏成片", "3个开头钩子版本", "中文字幕文件", "封面图1张"],
        acceptanceCriteria: ["前3秒明确呈现核心卖点", "画面比例适配抖音/小红书", "包含产品名称、利益点和行动引导"],
        suggestedQuestions: ["是否已有产品图片、Logo、品牌色或参考案例？", "是否需要创作者提供脚本？", "是否需要多版本测试？"]
      },
      createdAt: "2026-05-10"
    },
    {
      id: "p-2",
      buyerId: "u-buyer-2",
      title: "浴室免打孔收纳架电商主图套装",
      description: "为淘宝链接制作主图、详情场景图和一张活动横幅，突出防水、承重和安装便捷。",
      category: "Image Design",
      budget: 1800,
      deadline: "2026-05-30",
      status: "open",
      referenceFile: "产品照片.zip",
      agentBrief: {
        objective: "为浴室免打孔收纳架制作电商主图和详情页素材。",
        audience: "租房人群、小户型家庭和注重浴室收纳的电商用户",
        style: "清爽、可信、突出防水承重和安装便利",
        deliverables: ["主图1张", "场景图4张", "活动横幅1张", "可编辑源文件"],
        acceptanceCriteria: ["主视觉清晰呈现产品", "卖点文字不遮挡主体", "场景能体现安装和收纳效果"],
        suggestedQuestions: ["是否有实拍产品图？", "是否需要适配淘宝主图尺寸？", "是否有品牌字体和配色？"]
      },
      createdAt: "2026-05-12"
    },
    {
      id: "p-3",
      buyerId: "u-buyer-1",
      title: "B端SaaS onboarding数字人口播",
      description: "制作一条企业风数字人口播视频，包含脚本润色、普通话配音、字幕和最终视频文件。",
      category: "Digital Human",
      budget: 6800,
      deadline: "2026-06-08",
      status: "in_progress",
      createdAt: "2026-05-14"
    },
    {
      id: "p-4",
      buyerId: "u-buyer-2",
      title: "夏季咖啡店活动AI海报系列",
      description: "需要统一视觉方向和6张海报，用于朋友圈、小红书和门店屏幕。",
      category: "Image Design",
      budget: 4600,
      deadline: "2026-06-05",
      status: "matching",
      createdAt: "2026-05-16"
    },
    {
      id: "p-5",
      buyerId: "u-buyer-3",
      title: "线上课程数字人直播预告",
      description: "制作一条亲和力数字人预热视频，提炼课程卖点，包含两轮修改。",
      category: "Digital Human",
      budget: 5200,
      deadline: "2026-06-01",
      status: "completed",
      createdAt: "2026-05-01"
    },
    {
      id: "p-6",
      buyerId: "u-buyer-2",
      title: "电商团队AIGC商品内容内训",
      description: "希望找一位讲师为运营和设计团队做AIGC商品图、短视频脚本和提示词实操培训，最好能结合家居日用商品案例。",
      category: "AIGC Training",
      tags: ["企业内训", "AI商品图", "提示词", "工作坊"],
      useCase: "training",
      deliverableTypes: ["other"],
      urgency: "this_week",
      needInvoice: true,
      longTerm: true,
      acceptPlatformRecommend: true,
      trainingRequirement: {
        topics: ["AI商品图", "提示词工程", "AI短视频脚本"],
        audience: "电商运营和设计团队",
        headcount: 28,
        format: "offline",
        city: "上海",
        duration: "1天工作坊",
        goal: "让团队掌握商品图生成、卖点脚本和素材复用流程，形成可复用模板。",
        needCustomCases: true,
        needMaterials: true
      },
      budget: 15000,
      deadline: "2026-06-18",
      status: "open",
      referenceFile: "家居日用商品案例与品牌资料.zip",
      qualificationFile: "城野生活电商营业执照.pdf",
      contactEmail: "leo@urbanline.co",
      contactPhone: "021-6800-2210",
      agentBrief: {
        objective: "为电商团队寻找AIGC培训讲师，完成商品图、提示词和短视频脚本实操训练。",
        audience: "电商运营、设计和内容团队",
        style: "实操、案例驱动、可落地",
        deliverables: ["培训方案", "1天线下工作坊", "商品案例练习", "课件和工具清单"],
        acceptanceCriteria: ["结合家居日用真实商品案例", "学员能独立完成商品图提示词和短视频脚本", "提供可复用模板和课后材料"],
        suggestedQuestions: ["是否能基于我们的商品案例定制练习？", "是否提供课件和工具清单？", "是否支持课后答疑或陪跑？"]
      },
      createdAt: "2026-05-27"
    }
  ],
  matches: [
    { id: "m-1", projectId: "p-1", creatorId: "c-2", score: 94, reason: "短视频广告经验强，适合多钩子投放素材。" },
    { id: "m-2", projectId: "p-1", creatorId: "c-1", score: 90, reason: "新品短片作品多，意向预算区间匹配。" },
    { id: "m-3", projectId: "p-1", creatorId: "c-5", score: 86, reason: "熟悉电商商品内容包交付。" },
    { id: "m-4", projectId: "p-2", creatorId: "c-8", score: 92, reason: "商品场景图和目录图能力匹配。" },
    { id: "m-5", projectId: "p-2", creatorId: "c-3", score: 89, reason: "电商主图和精修经验丰富。" },
    { id: "m-6", projectId: "p-2", creatorId: "c-10", score: 81, reason: "意向预算适配，支持图片与内容包交付。" },
    { id: "m-7", projectId: "p-3", creatorId: "c-4", score: 95, reason: "数字人口播和脚本润色能力高度匹配。" },
    { id: "m-8", projectId: "p-3", creatorId: "c-9", score: 88, reason: "数字人与声音流程适合培训讲解。" },
    { id: "m-9", projectId: "p-3", creatorId: "c-10", score: 79, reason: "跨品类内容交付灵活。" },
    {
      id: "m-10",
      projectId: "p-6",
      creatorId: "c-9",
      score: 93,
      reason: "培训主题、数字人课件和线下工作坊经验匹配。",
      risk: "讲师主体待审核，建议先确认企业内训案例和可开票方式。",
      nextStep: "建议先确认培训对象、1天工作坊安排和家居商品案例范围。"
    },
    {
      id: "m-11",
      projectId: "p-6",
      creatorId: "c-4",
      score: 88,
      reason: "数字人与课程培训经验匹配，支持企业定制案例。",
      risk: "报价可能接近预算上限，建议先确认半日/全天范围。",
      nextStep: "建议确认课件、练习材料和课后答疑方式。"
    }
  ],
  orders: [
    {
      id: "o-1",
      projectId: "p-3",
      buyerId: "u-buyer-1",
      creatorId: "c-4",
      amount: 6800,
      status: "active",
      createdAt: "2026-05-17"
    },
    {
      id: "o-2",
      projectId: "p-5",
      buyerId: "u-buyer-3",
      creatorId: "c-9",
      amount: 5200,
      status: "approved",
      deliverableUrl: "https://example.com/course-avatar-final.mp4",
      createdAt: "2026-05-04"
    },
    {
      id: "o-3",
      projectId: "p-1",
      buyerId: "u-buyer-1",
      creatorId: "c-2",
      amount: 3600,
      status: "delivered",
      deliverableUrl: "https://example.com/lamp-ad-v1.zip",
      createdAt: "2026-05-18"
    }
  ],
  messages: [
    { id: "msg-1", orderId: "o-1", senderId: "u-buyer-1", body: "请保持口播语气稳重，整体风格偏企业服务，不要太娱乐化。", createdAt: "2026-05-18T09:30:00Z" },
    { id: "msg-2", orderId: "o-1", senderId: "u-creator-4", body: "收到。我会先发一版脚本润色稿，确认后再进入数字人渲染。", createdAt: "2026-05-18T10:04:00Z" },
    { id: "msg-3", orderId: "o-1", senderId: "u-creator-4", body: "第一版脚本已整理好，请确认卖点顺序。", attachmentUrl: "https://example.com/script-v1.docx", createdAt: "2026-05-19T08:15:00Z" },
    { id: "msg-4", orderId: "o-3", senderId: "u-creator-2", body: "已交付第一版，包含三个开头钩子和字幕文件。", attachmentUrl: "https://example.com/lamp-ad-v1.zip", createdAt: "2026-05-21T12:20:00Z" }
  ],
  reviews: [
    {
      id: "r-1",
      orderId: "o-2",
      buyerId: "u-buyer-3",
      creatorId: "c-9",
      rating: 5,
      comment: "交付很快，数字人风格和课程品牌很匹配。",
      createdAt: "2026-05-12"
    }
  ],
  reports: [],
  feedback: [],
  activityEvents: [
    { id: "a-1", userId: "u-buyer-1", role: "buyer", eventType: "login", createdAt: "2026-05-02T09:00:00Z" },
    { id: "a-2", userId: "u-buyer-1", role: "buyer", eventType: "post_project", targetType: "project", targetId: "p-1", createdAt: "2026-05-10T10:20:00Z" },
    { id: "a-3", userId: "u-buyer-1", role: "buyer", eventType: "invite_creator", targetType: "order", targetId: "o-3", createdAt: "2026-05-18T11:00:00Z" },
    { id: "a-4", userId: "u-buyer-2", role: "buyer", eventType: "login", createdAt: "2026-05-08T13:00:00Z" },
    { id: "a-5", userId: "u-buyer-2", role: "buyer", eventType: "post_project", targetType: "project", targetId: "p-2", createdAt: "2026-05-12T15:00:00Z" },
    { id: "a-6", userId: "u-buyer-3", role: "buyer", eventType: "approve_order", targetType: "order", targetId: "o-2", createdAt: "2026-05-12T18:00:00Z" },
    { id: "a-7", userId: "u-creator-2", role: "creator", eventType: "deliver_order", targetType: "order", targetId: "o-3", createdAt: "2026-05-21T12:20:00Z" },
    { id: "a-8", userId: "u-creator-4", role: "creator", eventType: "send_message", targetType: "order", targetId: "o-1", createdAt: "2026-05-18T10:04:00Z" },
    { id: "a-9", userId: "u-creator-9", role: "creator", eventType: "deliver_order", targetType: "order", targetId: "o-2", createdAt: "2026-05-10T17:00:00Z" },
    { id: "a-10", userId: "u-creator-1", role: "creator", eventType: "browse", targetType: "project", targetId: "p-1", createdAt: "2026-05-19T08:30:00Z" },
    { id: "a-11", userId: "u-creator-3", role: "creator", eventType: "browse", targetType: "project", targetId: "p-2", createdAt: "2026-05-20T11:30:00Z" },
    { id: "a-12", userId: "u-creator-8", role: "creator", eventType: "browse", targetType: "project", targetId: "p-2", createdAt: "2026-05-20T12:00:00Z" }
  ]
};
